# Generated by Django 4.1.1 on 2022-10-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_types',
            field=models.IntegerField(blank=True, choices=[(1, 'LIKE'), (2, 'COMMENT'), (3, 'FOLLOW'), (4, 'MESSAGE')], null=True),
        ),
    ]
