# Generated by Django 4.1.1 on 2022-10-06 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0002_notification_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ManyToManyField(blank=True, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
