# Generated by Django 4.1.1 on 2022-10-12 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_star_star'),
        ('notification', '0004_remove_notification_sender_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
    ]
