# Generated by Django 4.1.2 on 2022-10-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_notification_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_types',
            field=models.IntegerField(blank=True, choices=[(1, 'LIKE'), (2, 'COMMENT'), (3, 'FOLLOW'), (4, 'MESSAGE'), (5, 'DISCUSS')], null=True),
        ),
    ]
