# Generated by Django 4.1.2 on 2022-10-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatonetoone',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
