# Generated by Django 4.1.2 on 2022-10-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_discussbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussbook',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
