# Generated by Django 4.1.2 on 2022-10-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_discussbook_is_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussbook',
            name='is_start',
            field=models.BooleanField(default=False),
        ),
    ]
