# Generated by Django 4.1.2 on 2022-10-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_discussbook_is_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussbook',
            name='when',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
