# Generated by Django 4.1.1 on 2022-10-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_star_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='star',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
