# Generated by Django 4.1.2 on 2022-10-18 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0003_parentcomment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentcomment',
            name='dislikes',
            field=models.ManyToManyField(related_name='comment_dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
