# Generated by Django 4.1.1 on 2022-10-03 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('status', models.CharField(help_text="Ozinizdin' jonelisin'izdi kiritin!", max_length=50)),
                ('social_telegram', models.CharField(blank=True, max_length=60, null=True)),
                ('social_instagram', models.CharField(blank=True, max_length=60, null=True)),
                ('social_facebook', models.CharField(blank=True, max_length=60, null=True)),
                ('bio', models.TextField(blank=True, help_text="Ozin'iz haqqinda mag'liwmat!", null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
