# Generated by Django 4.1.1 on 2022-10-06 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myaccount', '0003_alter_follow_follower_alter_follow_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaccount',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
